name: environment test

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: environment
        options:
          - dev
          - stg
          - prod

env:
  environment: ${{ github.event.inputs.environment }}

permissions:
  id-token: write
  contents: read

jobs:
  environment-test:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: environment-test
        env:
          TEST_ENV: ${{ secrets.TEST_ENV }}
        run: |
          echo "$TEST_ENV" | base64 -d > test.txt
          cat test.txt